---
functional:
  - Требование 1 Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Требование 2 Пользователь должен иметь возможность фильтровать товары
  - Требование 3 Пользователь должен иметь возможность просматривать товары
  - Требование 4 Пользователь должен иметь возможность просматривать подробную информацию о товаре
  - Требование 5 Пользователь должен иметь возможность добавлять товары в корзину
  - Требование 6 Пользователь должен иметь возможность просматривать содержимое корзины
non-functional:
  - Требование 7 Сайт нужно разработать с учетом удобства использования
  - Требование 8 Сайт нужно оптимизировать для скорости работы
  - Требование 9 Сайт должен быть безопасным и защищать данные пользователя
  - Требование 10 Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Требование 11 Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Требование 12 Сайт должен иметь мобильную версию
  - Требование 13 Сайт должен быть доступным на различных устройствах 
implicit:
  - Требование 14 Пользователь должен иметь возможность зарегистрироваться на сайте
  - Требование 15 Сайт должен содержать пользовательское соглашение (политику конфиденциальности)
  - Требование 16 Сайт должен иметь Cookie-файлы
  - Требование 17 Пользователь должен иметь возможность воспользоваться формой обратной связи (чат-бот, обратный звонок)
  - Требование 18 Пользователь должен видеть контакты интернет-магазина
