---
test-cases:
  - summary: |
      Проверка работы кнопки "Магазин" при клике с любой страницы каталога в шапке страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка работы кнопки "Магазин" из карточки товара в шапке страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректного отображения кнопки "Корзина" в шапке страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка отображения добавленных товаров кнопки "Корзина" в шапке страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректного отображения кнопки "Язык" в шапке страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка работы кнопки "Язык" в шапке страницы интернет-магазина Hexlet Store
    status: fail

  - summary: |
      Проверка работы поля "Поиск" при вводе наименования товара из каталога интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка работы поля "Поиск" интернет-магазина Hexlet Store при вводе несуществующих товаров
    status: fail

  - summary: |
      Проверка корректной работы поля "Поиск" интернет-магазина Hexlet Store на всех страницах сайта, кроме главной
    status: fail

  - summary: |
      Проверка корректного отображения списка категорий товаров фильтра "Категория" на всех страницах сайта интернет-магазина Hexlet Store
    status: fail

  - summary: |
      Проверка работы фильтра "Категория" на всех страницах сайта интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка отображения фильтра "Производитель" на всех страницах сайта интернет-магазина Hexlet Store
    status: fail

  - summary: |
      Проверка корректной работы фильтра "Производитель" на всех страницах сайта интернет-магазина Hexlet Store
    status: fail

  - summary: |
      Проверка отображения фильтра "В наличии" на всех страницах сайта интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы фильтра "В наличии" в выбранном состоянии на всех страницах сайта интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы фильтра "В наличии" в невыбранном состоянии на всех страницах сайта интернет-магазина Hexlet Store
    status: fail

  - summary: |
      Проверка корректной работы фильтра "Цена" на всех страницах сайта интернет-магазина Hexlet Store
    status: fail

  - summary: |
      Проверка корректной работы фильтра "Цена" на всех страницах при вводе чисел, дробных чисел с точкой и запятой
    status: fail

  - summary: |
      Проверка работы фильтра "Цена" на всех страницах при вводе отрицательных чисел, нуля, пустого значения, символа "+"; "."; ","
    status: fail

  - summary: |
      Проверка работы меню фильтрации на всех страницах сайта интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы кнопки "Следующая" в каталоге товаров страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы кнопки "Предыдущая" в каталоге товаров страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректного отображения карточки товара в каталоге товаров страницы интернет-магазина Hexlet Store
    status: fail

  - summary: |
      Проверка корректной работы карточки товара в каталоге товаров страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы размещенной ссылки в карточке товара страницы интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы кнопки "Добавить в корзину" в карточке товара со страницы каталога/со страницы карточки товара
    status: pass

  - summary: |
      Проверка работы перехода со страницы карточки товара обратно в магазин, в корзину, в каталог интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы корзины в интернет-магазине Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы кнопки "Очистить корзину" в корзине интернет-магазина Hexlet Store
    status: fail

  - summary: |
      Проверка корректной работы кнопки "Продолжить покупки" в корзине интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректного расчета суммы "Итого" в корзине интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректного отображения суммы "Итого" в корзине интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректной работы кнопки "Оформить заказ" в корзине интернет-магазина Hexlet Store
    status: pass

  - summary: |
      Проверка корректного отображения всплывающего окна "Заказ успешно оформлен" в корзине интернет-магазина
    status: pass

  - summary: |
      Проверка корректной работы всплывающего окна "Заказ успешно оформлен" в корзине интернет-магазина Hexlet Store
    status: fail

bugreports:
  - summary: |
      Некорректная работа нопки "Язык" в шапке страницы интернет-магазина Hexlet Store
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть любую страницу каталога интернет-магазина
      - Нажать на кнопку «Язык» в шапке страницы интернет-магазина
      - Выбрать из выпадающего списка и кликнуть на "Русский"
    expected-result: |
      Пользователь должен увидеть отображение текста и цены на сайте с полным переводом на русский язык
    actual-result: |
      Перевод на русский язык на сайте осуществлен неполностью

  - summary: |
      Некорректная работа поля "Поиск" интернет-магазина при вводе несуществующих товаров
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть любую страницу каталога интернет-магазина
      - Перевести курсор в поле "Поиск"
      - Набрать наименование товара не из каталога "scarf"
    expected-result: |
      Пользователь должен увидеть отображение сообщения "Ничего не найдено!"
    actual-result: |
      На странице сайта ничего не изменилось

  - summary: |
      Некорректная работа поля "Поиск" интернет-магазина на всех страницах сайта, кроме главной
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть вторую страницу каталога интернет-магазина
      - Перевести курсор в поле "Поиск"
      - Набрать наименование товара из каталога "Essence"
    expected-result: |
      При вводе в поле "Поиск" наименования любого товара из каталога происходит поиск и выдача информации на всех страницах сайта одинаково
    actual-result: |
      При вводе в поле "Поиск" наименования любого товара из каталога происходит выдача информации не по запросу

  - summary: |
      Содержание выпадающего списка фильтра "Категрия" отображается на всех страницах сайта одинаково
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть главную страницу каталога интернет-магазина
      - Нажать кнопку "Категория"
      - Пролистать страницы каталога интернет-магазина
    expected-result: |
      Выпадающий список фильтра "Категория" на всех страницах интернет-магазина отображается с одинаковым содержанием
    actual-result: |
      Выпадающий список фильтра "Категория" на всех страницах интернет-магазина отображается с разным содержанием

  - summary: |
      Некорректное отображение фильтра "Производитель" на всех страницах интернет-магазина
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть главную страницу каталога интернет-магазина
      - Просмотреть фильтр "Производитель"
      - Пролистать страницы каталога интернет-магазина
    expected-result: |
      Все чек-боксы фильтра "Производитель" на всех страницах интернет-магазина отображаются с одинаковым содержанием, полностью заполнены 
    actual-result: |
      В фильтре "Производитель" чек-боксы на каждой странице заполнены по разному, имеются не заполненные совсем

  - summary: |
      Нет возможности проверить работу фильтра "Производитель" на всех страницах интернет-магазина
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть вторую страницу каталога интернет-магазина
    expected-result: |
      Все чек-боксы фильтра "Производитель" на всех страницах интернет-магазина отображаются с одинаковым содержанием, полностью заполнены 
    actual-result: |
       Чек-бокс в фильтре "Производитель" на следующей странице интернет-магазина всего один и не заполнен

  - summary: |
      Некорректная работа фильтра "В наличии" на всех страницах интернет-магазина
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть главную/следующую страницу каталога интернет-магазина
      - Снять галочку в чек-боксе фильтра "В наличии"
    expected-result: |
      Пользователь должен увидеть все карточки товаров каталога на всех страницах, которые есть в наличии и которых нет в наличии
    actual-result: |
       Если снять галочку в чек-боксе фильтра "В наличии" на главной странице каталога, перейти на следующую страницу нет возможности

  - summary: |
      Некорректная работа фильтра "Цена" на всех страницах интернет-магазина
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть главную/следующую страницу каталога интернет-магазина
      - Проставить в поле фильтра "Цена" корректные значения, например: от 5 до 2088
    expected-result: |
      Пользователь должен увидеть отображение всех карточек товаров каталога в данной ценовой категории
    actual-result: |
       При вводе коррекных значений в поле фильтра "Цена" выводятся товары всех ценовых категорий каталога, без учета фильтрации

  - summary: |
      Некорректная работа фильтра "Цена" на всех страницах интернет-магазина при вводе дробных чисел, чисел с запятой и точкой.
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть главную/следующую страницу каталога интернет-магазина
      - Проставить в поле фильтра "Цена" корректные значения, например: от 9,27 до 9.27
    expected-result: |
      Пользователь должен увидеть отображение всех карточек товаров каталога в данной ценовой категории
    actual-result: |
       При вводе дробных значений в поле фильтра "Цена" выводятся товары всех ценовых категорий каталога, без учета фильтрации

  - summary: |
      Некорректное отображение карточек товаров на всех страницах интернет-магазина 
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть главную/следующую страницу каталога интернет-магазина
      - Просмотреть отображение выведенных карточек товаров в каталоге
    expected-result: |
      Пользователь должен увидеть отображение всех карточек товаров каталога в едином стиле
    actual-result: |
       Выводимые в каталоге карточки товаров имеют лишние элементы и отличаются по размеру фото

  - summary: |
      Некорректная работа кнопки "Очистить корзину" в корзине интернет-магазина 
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть главную/следующую страницу каталога интернет-магазина
      - Положить товар в корзину
      - Перейти в корзину
      - Нажать на кнопку "Очистить корзину"
      - Нажать на кнопку "Магазин" в шапке страницы
    expected-result: |
      Пользователь должен увидеть отображение пустой корзины
    actual-result: |
       После клика по кнопке "Очистить корзину" и возврата через кнопку "Магазин", товары из корзины не удаляются, количество товаров
       отображается над кнопкой "Корзина" в шапке страницы

  - summary: |
      Некорректная работа всплывающего окна "Заказ успешно оформлен" в корзине интернет-магазина 
    environment: |
      Яндекс Браузер, Windows 11, (64 бит)
    steps-to-reproduce: |
      - Зайти на сайт интернет-магазина Hexlet Store https://products-store-git-v2bugfixes-hexlet-components.vercel.app/cart
      - Открыть главную/следующую страницу каталога интернет-магазина
      - Положить товар в корзину
      - Перейти в корзину
      - Нажать на кнопку "Оформить заказ"
      - Нажать на иконку "Крестик" в верхней части всплывающего окна "Заказ успешно оформлен"
    expected-result: |
      У пользователя есть возможность закрыть всплывающее окно "Заказ успешно оформлен" при помощи клика по иконке "Крестик"
    actual-result: |
       После клика по иконке "Крестик" во всплывающем окне "Заказ успешно оформлен" ничего не происходит
